name: "[schedule] weekly"
# badFileName.js @Monday
# mostTranscludedPages.js @Tuesday
# shortPages.js @Wednesday
# tentativeTitle.js @Wednesday
# checkEditgroupActivities.js @Thursday
# fileRevisionDelete.js @Thursday
# needImprove.js @Friday
# needImproveWelcome.js @Friday

on:
  schedule:
    - cron: "55 21 * * 0" # Monday 05:55 CST
    - cron: "55 21 * * 1" # Tuesday 05:55 CST
    - cron: "55 21 * * 2" # Wednesday 05:55 CST
    - cron: "55 21 * * 3" # Thursday 05:55 CST
    - cron: "55 21 * * 4" # Friday 05:55 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "bad-file-name"
          - "most-transcluded-pages"
          - "short-pages"
          - "tentative-title"
          - "check-editgroup-activities"
          - "file-revision-deletion"
          - "need-improve"
          - "need-improve-welcome"
      group:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "need-improve"
          - "all"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bad-file-name:
    if: |
      github.event.schedule == '55 21 * * 0' || 
      github.event.inputs.task == 'bad-file-name' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run mostTranscludedPages.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
          CM_IBOT: ${{ secrets.CM_IBOT }}
        run: node src/badFileName.js

  most-transcluded-pages:
    if: |
      github.event.schedule == '55 21 * * 1' || 
      github.event.inputs.task == 'most-transcluded-pages' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run mostTranscludedPages.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
        run: node src/mostTranscludedPages.js

  short-pages:
    if: |
      github.event.schedule == '55 21 * * 2' || 
      github.event.inputs.task == 'short-pages' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run shortPages.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
        run: node src/shortPages.js

  tentative-title:
    if: |
      github.event.schedule == '55 21 * * 2' || 
      github.event.inputs.task == 'tentative-title' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tentativeTitle.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
        run: node src/tentativeTitle.js

  check-editgroup-activities:
    if: |
      github.event.schedule == '55 21 * * 3' || 
      github.event.inputs.task == 'check-editgroup-activities' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run checkEditgroupActivities.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
          CM_IBOT: ${{ secrets.CM_IBOT }}
        run: node src/checkEditgroupActivities.js

  file-revision-deletion:
    if: |
      github.event.schedule == '55 21 * * 3' || 
      github.event.inputs.task == 'file-revision-deletion' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run fileRevisionDelete.js
        env:
          CM_ABOT: ${{ secrets.CM_ABOT }}
        run: node src/fileRevisionDelete.js

  need-improve:
    if: |
      github.event.schedule == '55 21 * * 4' || 
      github.event.inputs.task == 'need-improve' ||
      github.event.inputs.group == 'need-improve' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run needImprove.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
        run: node src/needImprove.js

  need-improve-welcome:
    if: |
      github.event.schedule == '55 21 * * 4' || 
      github.event.inputs.task == 'need-improve-welcome' ||
      github.event.inputs.group == 'need-improve' ||
      github.event.inputs.group == 'all'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run needImproveWelcome.js
        env:
          ZH_IBOT: ${{ secrets.ZH_IBOT }}
        run: node src/needImproveWelcome.js
