name: "[cron] 4x/d @daily"
# userpageDelete.js
# redirectDelete.js
# nulleditInCategory.js

on:
  schedule:
    - cron: "35 19,2,9,14 * * *"
    # 3:35, 10:35, 17:35, 22:35 CST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run userpageDelete.js
        env:
          MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/userpageDelete.js

      - name: Run redirectDelete.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/redirectDelete.js

      - name: Run nulleditInCategory.js
        env:
          MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
          ZH_BOT: ${{ secrets.ZH_BOT }}
          CM_BOT: ${{ secrets.CM_BOT }}
        run: node src/nulleditInCategory.js
