name: "Blocked"

on:
  schedule:
    - cron: "55 21 * * 3" # Thursday 05:55 CST
    - cron: "50 16 11,26 * *" # 12th, 27th 00:50 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        default: "none"
        options:
          - "none"
          - "mark-abuser-status"
          - "remove-userrights"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mark-abuser-status:
    if: |
      github.event.schedule == '9 9 9 9 9' || 
      github.event.inputs.task == 'mark-abuser-status'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/Blocked/markAbuserStatus.js

  remove-userrights:
    runs-on: ubuntu-latest
    if: |
      github.event.schedule == '50 16 13 * *' || 
      github.event.inputs.task == 'remove-userrights'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Script @14th
        env:
          ZH_ABOT: ${{ secrets.ZH_ABOT }}
        run: node src/Blocked/removeUserrights.js