name: "[manually] deletion"

on:
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        default: "none"
        options:
          - "deletion"
          - "none"
      site:
        type: choice
        required: false
        default: "all"
        options:
          - "zh"
          - "cm"
          - "all"

env:
  MOEGIRL_API_USER_AGENT: ${{ secrets.MOEGIRL_API_USER_AGENT }}

jobs:
  zh-deletion:
    if: |
      github.event.inputs.task == 'deletion' &&
      (github.event.inputs.site == 'zh' || github.event.inputs.site == 'all')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run delete.js
        env:
          SITE: "zh"
          ZH_MAIN: ${{ secrets.ZH_MAIN }}
        run: node src/delete.js

  cm-deletion:
    if: |
      github.event.inputs.task == 'deletion' &&
      (github.event.inputs.site == 'cm' || github.event.inputs.site == 'all')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run delete.js
        env:
          SITE: "cm"
          CM_MAIN: ${{ secrets.CM_MAIN }}
        run: node src/delete.js
