name: Check for Modified JavaScript Files

on:
  push:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: get_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > changed_files.txt
          mapfile -t files < changed_files.txt
          echo "::set-output name=files::${files[*]}"

      - name: Check if array contains .js files
        id: check_js_files
        run: |
          contains_js=false
          for file in "${{ steps.get_files.outputs.files }}"; do
            if [[ $file == *.js ]]; then
              contains_js=true
              break
            fi
          done
          echo "::set-output name=contains_js::$contains_js"

      - name: Print result
        run: |
          echo "Modified files: ${{ steps.get_files.outputs.files }}"
          echo "Contains .js files: ${{ steps.check_js_files.outputs.contains_js }}"

  use_var:
    runs-on: ubuntu-latest
    needs: check_files
    if: !needs.check_files.outputs.contains_js

    steps:
      - run: echo "Do something with ${{ needs.get_files.outputs.files }}"
